export enum SpendingActionTypes {
    ADD = 'add',
    EDIT = 'edit',
    DELETE = 'delete'
}

export const SpendingCategories = [
   'Groceries',
    'Restaurants',
    'Coffee Shops',
    'Takeout & Delivery',
    'Public Transit',
    'Cab',
    'Vegetables',
    'Fuel/Gas',
    'Vehicle Maintenance',
    'Ride Sharing (e.g., Uber, Lyft)',
    'Rent/Mortgage',
    'Utilities (Electricity, Water, Gas)',
    'Home Maintenance',
    'Property Taxes',
    'Medical Bills',
    'Health Insurance',
    'Pharmacy/Prescriptions',
    'Dental Care',
    'School Supplies',
    'Tuition Fees',
    'Online Courses',
    'Books',
    'Electronics',
    'Software',
    'Subscriptions',
    'Memberships',
    'Donations',
    'Gifts',
    'Clothing',
    'Shoes',
    'Accessories',
    'Personal Care',
    'Cleaning Supplies',
    'Laundry',
    'Gym Membership',
    'Sports Equipment',
    'Sporting Events',
    'Concerts',
    'Movies',
    'Music',
    'Video Games'
];
